 <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
 <style>
#prodTbl {
    text-transform: uppercase;
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;

}

.col-grp input{
    width:70%!important;  
    height:30px!important;
    margin-top:10px!important;
}
#addmorefields tr:nth-child(odd) { background-color: #f2f2f2; }
#addmorefields tr:hover { background-color: #ddd; }
#prodTbl th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: center;
    background-color: burlywood;
    color: black;
    font-weight: bold;
    font-size: 15px;
}

.asdasdselect{
  background:transparent;
   width: 170px;
   padding: 2px;
   font-family:Arial, Helvetica, sans-serif;
   font-size:11px;
   font-weight:600;
   color:#000;
   line-height: 1;
   border: 0;
   border-radius: 0;
   height: 22px;
  -webkit-appearance: none;
 
  }

.aselect-div, #aaddmorefields input, .acol-grp input{
    width: 170px;
    height: 27px;
    overflow: hidden;
    background: url(arrowhead.png) no-repeat right #fff;
    border-top:#575757 1px solid;
    -webkit-border-radius: 4px 4px 4px 4px;
     -moz-border-radius: 4px 4px 4px 4px;
          border-radius: 4px 4px 4px 4px;
    -webkit-box-shadow: inset 0 2px 4px rgba(107, 105, 105, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
     -moz-box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
          box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
          -moz-box-shadow:    0px 8px 3px -9px #000000;
          -webkit-box-shadow: 0px 8px 3px -9px #000000;
          box-shadow:         0px 8px 3px -9px #000000;
}

select > option {
  background: pink;
}
.col-grp input {
    margin-bottom: 5px;
}

</style>
<?php
$check = Mage::helper('adminhtml')->getUrl('admin_customorders/adminhtml_corders/addnew', ['_secure' => true,'tid'=>123]);

$resource = Mage::getSingleton('core/resource');
$readConnection = $resource->getConnection('core_read');
$writeConnection = $resource->getConnection('core_write');


$collection = Mage::getModel("customorders/cprods")->getCollection();

$products = array();
foreach($collection as $prod){
	 $products[] = $prod->getData();
}
?>
<?php
if($_POST['submit']!='') {
    if(count($_POST['items'])){
        $_POST['items'] = json_encode($_POST['items']);

        $postdata = array();
        unset($_POST['submit']);

        $_POST['quote'] = "#ORDER-".time()." for ". $_POST['name'];
        foreach($_POST as $key=>$val) {
            $val = addslashes($val);
            $postdata[] = "$key='$val'";
        }
        var_dump($_POST);

        //mysql_query_cheat("INSERT INTO tbl_corders SET ".implode(",", $postdata));
        $success  = 1;
    }
}

$field[] = array("type"=>"text","value"=>"referrer","label"=>"Referrers Username");
$field[] = array("type"=>"text","value"=>"name","label"=>"Buyer Name");
$field[] = array("type"=>"text","value"=>"address","label"=>"Buyer Address");
$field[] = array("type"=>"text","value"=>"mobile","label"=>"Mobile/Phone");

$field[] = array("type"=>"select","value"=>"pickup","option"=>array("Yes","No"),"label"=>"Pickup?");

if($error!='') {
?>
<div class="warning"><ul class="fa-ul"><li><?php echo $error;?></li></ul></div>
<?php
}
?>

<?php

if($success!='') {

?>

<div class="noti"><ul class="fa-ul"><li><i class="fa fa-check fa-li"></i>Done submitting your orders <?php echo $_POST['quote']; ?>.</li></ul></div>

<?php

}

?>

<form method='POST' action='' class="form-container">
    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
        <h2>Create Order</h2>
    <div class="col-grp">
        <input required="" readonly type="hidden" name="quote" id="quote" size="40" maxlength="255" value="xxx" placeholder="Referrer">
        <hr>
        <?php
                        $is_editable_field = 1;

                        foreach($field as $inputs)

                        {

                                                if($inputs['label']!='')

                                                {

                                                $label = $inputs['label'];

                                                }

                                                else

                                                {

                                                $label = ucwords($inputs['value']);

                                                }

                        ?>

                                    <!---weee--->

                                            <!-- <td style="width:180px;" class="key" valign="top" ><label for="accounts_name"><?php echo $label; ?><?php echo $req_fld?>:</label></td> -->

                                            <?php if ( $is_editable_field ) { ?>

                                            <div class="col col-12">

                                            <?php

                                            if ($inputs['type']=='select')

                                            {

                                                if($$inputs['value']!='' && $inputs['value']=='code_id')

                                                { 


                                                }

                                                else

                                                {

           

                                                ?>
                                                <?php echo $inputs['label']; ?>
                                                <select name="<?php echo $inputs['value']; ?>" id="<?php echo $inputs['value']; ?>" required <?php echo $inputs['attr']; ?>>

                                                <?php

                                                foreach($inputs['option'] as $val)

                                                {

                                                    ?>

                                                    <option <?php if($$inputs['value']==$val){echo"selected='selected'";} ?> value='<?php echo $val;?>'><?php echo $val;?></option>

                                                    <?php

                                                }

                                                ?>

                                                </select>

                                                <span class="validation-status"></span>

                                                <?php

                                                }

                                            }

                                            else

                                            {

                                                ?>

                                                <input required <?php echo $inputs['attr']; ?> type="<?php echo $inputs['type']; ?>" name="<?php echo $inputs['value']; ?>" id="<?php echo $inputs['value']; ?>" size="40" maxlength="255" value="<?php echo $$inputs['value']; ?>" placeholder="<?php echo $label; ?>" />

                                                <span class="validation-status"></span>                                             

                                                <?php

                                            }

                                            ?>



                                            </div>

                                            <?php } else { ?>

                                            <div class="col col-12"><?php echo $$inputs['value']; ?></div>

                                            <?php } ?>                                                                                                    

                        <?php

                        }

                        ?>



    </div>




<style>
.itemstable td{
    padding:5px;
}
input.qtydats {
    width: 57px!important;
}
</style>

<?php
$selectdata = array();
 foreach($products as $prod){
    $prod['price'] = number_format($prod['price'],2);
    $selectdata[] = "<option value='{$prod['id']}'>{$prod['name']} - {$prod['price']}</option>";
 }
?>


<script>

    function removeorder(id){
        jQuery('#orderitems'+id).remove();
    }
    function addmorefields(){

        var optiondata = "<?php echo implode("", $selectdata); ?>";
        var startingids = parseInt(jQuery('.selectdata').length) + 1;

        jQuery('#addmorefields').append("<tr id='orderitems"+startingids+"'><td><div class='select-div'><select class='selectdata' name='items["+startingids+"][name]'>"+optiondata+"</select></div></td><td><input required class='qtydats' type='number' name='items["+startingids+"][qty]'></td><td><a onclick='removeorder("+startingids+")' href='javascript:void(0)'>Remove</td></tr>");
    }
    

</script>


<div class='itemstable'>
    Add Products: <a  onclick='addmorefields()'href='javascript:void(0);'>Add more</a>
        <table border='1' padding='1' width='100%' id="prodTbl">
                <tr>
                    <th>Product</th>
                    <th>Qty</th>
                    <th>Action</th>
                </tr>
            <tbody id='addmorefields'>
                
            </tbody>

        </table>
</div>



<div class="action"><input class='nbtn nbtn-primary' type='submit' name='submit' value='Send Order'></div>

</form>

<script type="text/javascript">
jQuery.noConflict();
jQuery( document ).ready(function() {
    addmorefields();
});  
</script>